### ISSUE TITLE
Visuals in State 1

### ISSUE THREAD

**Issue by bilbaeno** [hp1932/cis510GameProject#1]
I wanted to start a discussion about the visual representation of actions in the first state of the game, when customers are making purchases.

Using one of the kenney asset packs I mocked up this Drive Thru:
![drivethru_mockup](https://cloud.githubusercontent.com/assets/7476120/14725507/22fccc6c-07d1-11e6-852c-b1b510fd47c3.png)

I was thinking that a Drive Thru may be a better route to take as far as visual representation goes for the following reasons:
- animating the cars will be trivial compared to a person
- making the appearance of the cars vary will also be cheaper
- progress could be shown through upgrades to the players restaurant through scale/color/decoration

Regarding the art style of the later phases of the game: I think the pixel art for phase 1 could mesh just fine with the modular character pack Sol has been using for phase 2/3, we just need a consistent UI across the board tying them together.

Does anyone have any preference for showing the inside or outside of our establishment? Cons of the Drive Thru idea?

**Comment by hp1932** [comment]
This looks great! I agree that a drive-through would be much easier to implement and would probably look cleaner in the long run, especially given our time constraints.

Showing the exterior would be easier to do, I think, but I am wondering if it would highlight what is really important to the gameplay. Here are my thoughts

**Exterior View**
PROS:
- Easy to implement using existing sprites
- User can easily see when customers are arriving (not sure how important that is for gameplay, though)
- Gives the user a more "monitoring" role, rather than seeing down "into the trenches" as it were

CONS:
- May be difficult to show the ingredient levels and other important statuses (unless we also show a view into the storage room or have some other UI element indicating food levels)

**Interior View**
PROS:
- Easy to show ingredient levels in a storage room or something within the scene itself, rather than just UI
- A focus on where the action is taking place

CONS:
- Showing customer sprites is more difficult to animate and randomize, as well as match the visual style

I suppose we could have a half-and-half view, showing both inside and out somehow. What do you think? Really the main problem comes with how we want to display the food levels. This is assuming that we want to actually show them to the player during this first phase of gameplay instead of having them display only at the reporting stage.

**Comment by bilbaeno** [comment]
I like the half-and-half view idea.

To keep with the theme of keeping it easy to animate, what about the drive thru view + the walk-in fridge/pantry view?

There are a number of sprites for boxes, both empty and full, which could be used to represent the various ingredients the player is managing. 

Another benefit of the store room is that we once again don't have to animate customers or employees. Just boxes on shelves.

**Comment by hp1932** [comment]
Yeah, that sounds like a good solution. The boxes could represent a certain amount of the ingredient, or we could have some other count over each box so the player knows exactly how many are left, instead of just getting a different sprite when they run out.

**Comment by bilbaeno** [comment]
Here are the boxes. If we go this route I could add more varieties if needed.

![boxes_mockup](https://cloud.githubusercontent.com/assets/7476120/14726151/02e8b086-07d5-11e6-8421-535a29941c0f.png)

**Comment by hp1932** [comment]
Hmm yeah, those could work!

**Comment by bilbaeno** [comment]
store room view mockup:
![storeroom_mockup_4x](https://cloud.githubusercontent.com/assets/7476120/14727057/35253716-07dc-11e6-903a-6db45a734b2a.png)

**Comment by hp1932** [comment]
Yeah, that looks good! That artwork package is really nice.
