### ISSUE TITLE
Customer Creation Logic

### ISSUE THREAD

**Issue by hp1932** [hp1932/cis510GameProject#2]
- [x] - Randomly select from an array of customers to spawn in. 
- [x] - Make spawn times random between some range
- [x] - Animate customers moving to window, pausing, then leaving the screen
- [x] - Ensure that customers do not run into or pass one another

**Comment by hp1932** [comment]
Right now I have customers spawning from one point at a random rate, moving toward the drive-thru window, pausing then they get there, then leaving the screen after a set wait time. 

I am working on how to have the customers "queue up" in the drive thru so they will wait in line if there is already a customer being served. I've considered using rigidbodies and having physics take care of it, but they just push each other. I'm now thinking about using triggers to stop the customers when they collide, but I am not sure how that will work because they will both have the same scripts and both onTriggerEnter functions will trigger, thus stopping both of them. Only one customer should stop.

Let me know if you have suggestions on how to do this! I'll continue thinking about it.

**Comment by solcjoye** [comment]
Hannah, not sure if this will go through Git as I'm replying to the email on my phone... But what if there are circles or somethin where the AI characters go through instead of colliding w each other... The circle could just be a trigger w no physical effects. If circle empty the player moves to next if next circle filled by other player they go to next empty circle... So it's dependent on the circle being filled by player (Boolean yes no) vs an actual collision... If that makes sense if not I can sketch out when I'm home in a few hours.

Sol Joye
Instructional Design Coordinator
Global and Online Ed
University of Oregon

----- Reply message -----

**Comment by bilbaeno** [comment]
I think you could create an array of positions and have the customers move to the next available position in the array.

So when a new customer is created, they check the array for the first available position, then move to it. If the window is full, this would be the menu spot. If the menu spot is full, this would be first in line. If first in line is full, they go to second. Etc. After a customer is done ordering, you pop them off the array and everyone moves up one.

**Comment by solcjoye** [comment]
Yeah, I think Adam and I are on the same page, he just used big words like array and I used slightly less big words like circle... :)

Sorry - had kid things today, up at OSU all day at a soccer tournament. I am planning on spending several hours tomorrow starting to work on some of this...

**Comment by hp1932** [comment]
Ah yes, that's a good idea. Thank you both. I will look into implementing that today.

I don't have any of the economy AI done yet, unfortunately, as I've been really sick again. I'll try to get as much done as possible before Tuesday.

**Comment by hp1932** [comment]
Customers are now waiting in line based on an array of positions, as per the suggestion here. The basics of customers spawning is working with prototyped images. Still needs artwork, but the logic is there. This work ticket is now completed.
