### ISSUE TITLE
Scene Switch: Reports to Graph & Purchasing

### ISSUE THREAD

**Issue by chapman3** [hp1932/cis510GameProject#23]
Need 2 buttons, one to switch from the initial report scene to the demand curve graph and one to the purchasing stage.

**Comment by hp1932** [comment]
Buttons and code hookups have been added. NOTE: There is no "return to report" button on the graph yet. I know the graph is still being worked on, and since adding a button is quick and easy, I thought I'd wait to include it once the graph is done. All the code is ready, so adding the button should be simple.
