### ISSUE TITLE
BUG: Reporting/Global values break after return to scene 1

### ISSUE THREAD

**Issue by bilbaeno** [hp1932/cis510GameProject#25]
If you start the game in Scene 1, go through the report and purchasing, then go to the next day (back to Scene1) all of the reporting breaks.

I believe it is due to some global values not resetting at the start of scene 1. All of my code for printing the reports works off of the Global Restaurant Statistics, which is why I think it is an issue with that and not with my printing but I could be very wrong.

Posting here because I am unable to troubleshoot it at the moment. I'll look at it when I get some free time, but if someone else has time today please see if you can figure out what's going on. Just pushed my latest work so you should be able to see what I'm talking about.

**Comment by bilbaeno** [comment]
Changing

```
public void SwitchToSimulation()
    {
        SceneManager.LoadScene ("phase1");
        GlobalControl.Instance.savedPlayerData.ResetValuesForPhase1 ();

    }
```

to

```
public void SwitchToSimulation()
    {
        GlobalControl.Instance.savedPlayerData.ResetValuesForPhase1 ();
        SceneManager.LoadScene ("phase1");
    }
```

solved some of the issues. 

Customers seem to stop purchasing things after 2 days have passed though. Is this maybe something to do with one of the economy variables? I haven't read into the code on that too much.

**Comment by bilbaeno** [comment]
Current bug status:
- [x] no orders are being placed after day1
- [x] dish prices for Ham and Veggie are not being loaded after day 1 (report phase)

EDIT: Orders not being placed after day1 seems to be the only issue now.

**Comment by hp1932** [comment]
**Cause**: This was caused by condiments and cheese being used in recipes, but these ingredients were not available to purchase. As soon as they ran out, customers were not being served.

**Temporary fix:** Removed cheese and condiments from all sandwich recipes.

**Future fix:** Add ingredients to purchase screen and phase 1 storage space after modularizing purchase display code

**Commit with Temporary Fix:** https://github.com/hp1932/cis510GameProject/commit/6ce0fa56d0bdc7655e6afa6ee530229b7343634c
