### ISSUE TITLE
Phase 1: Graphic/visual cue for customer orders

### ISSUE THREAD

**Issue by hp1932** [hp1932/cis510GameProject#8]
We need to show what the customer is ordering to give player feedback.
There should also be some indicator (maybe of customer mood?) to show if a customer was not served.

**Comment by bilbaeno** [comment]
I'll create some speech bubble type icons that can pop up next to the cars as they drive off. I think a scale of 1-5 should be enough.

**Comment by hp1932** [comment]
Since we are only basing satisfaction off of whether or not they were served everything they ordered (I assume), a 1-5 scale probably way more than enough. The simplest solution would be having a binary happy/unhappy rating.

**Comment by bilbaeno** [comment]
Having character faces pop up next to the cars was not working, due to how fast the cars move.

I've added a "last customer" section to the UI to show whether or not the last customer was satisfied with your service.

I'll work on making the transition more clear, and showing more than just a sad or happy face for feedback.

**Comment by hp1932** [comment]
The faces shown in the simulation look good. I am wondering if we still want to have some indication of what each customer orders within the simulation.
